web/models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def init_app(app):
    print(app.config["SQLALCHEMY_DATABASE_URI"])
    db.init_app(app)
    with app.app_context():
        db.create_all()

web/models/folios.py
from . import db

class Folio(db.Model):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )

    name = db.Column(db.String)
    email = db.Column(db.String)

    biography = db.Column(db.String)
    education = db.Column(db.String)
    skills = db.Column(db.String,default = "", nullable=True) 

web/models/users.py
from flask_login import UserMixin
from . import db

class User(db.Model, UserMixin):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    password = db.Column(db.String, unique=True, nullable=False)
    email = db.Column(db.String)

    first_name = db.Column(db.String)
    last_name = db.Column(db.String)

web/forms/accounts.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators


class LoginForm(FlaskForm):
    email = StringField(
        "name", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password = StringField(
        "password",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3, message="มากกว่า 3"),
        ],
    )


class RegisterForm(FlaskForm):
    email = StringField(
        "email", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password = StringField(
        "password",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3, message="มากกว่า 3"),
        ],
    )
    first_name = StringField("first_name", validators=[validators.DataRequired()])
    last_name = StringField("password", validators=[validators.DataRequired()])

    

web/forms/folios.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators
from wtforms import widgets


class FolioForm(FlaskForm):
    email = StringField(
        "email", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    name = StringField("Name", validators=[validators.DataRequired()])
    biography = StringField("Biography", widget=widgets.TextArea())
    education = StringField("Education", widget=widgets.TextArea())
    skills = StringField("Skills", validators=[validators.DataRequired()])

web/main.py
from flask import Flask, render_template, redirect, url_for
from flask_login import LoginManager

from views import accounts
from views import folios
from views import classes
import models
from models import users

import os

login_manager = LoginManager()
login_manager.login_view = "accounts.login"



@login_manager.unauthorized_handler
def unauthorized():

    print("You don't have permission")
    return redirect(url_for("accounts.login"))


app = Flask(__name__)


@login_manager.user_loader
def load_user(user_id):
    user = models.db.session.query(users.User).filter_by(id=user_id).first()
    return user


@app.route("/")
def index():
    return render_template("main/index.html")


    
if __name__ == '__main__':
    app.secret_key = "my super secret key that no one"  # import os // os.get_env['SECRET_KEY']
    login_manager.init_app(app)

    # app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///:memory"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{os.getcwd()}/db/project.db"
    models.init_app(app)

    app.register_blueprint(accounts.bp)
    app.register_blueprint(folios.bp)
    app.register_blueprint(classes.bp)

    app.run(debug=True)

web/views/accounts.py
from flask import (
                Blueprint, 
                render_template, 
                request, redirect, 
                url_for
                )
from flask_login import (
                login_required, 
                login_user, 
                logout_user
                )

from werkzeug.security import (
                generate_password_hash, 
                check_password_hash
                )

from forms import accounts as accounts_form
import models
from models import users
from models import folios

bp = Blueprint("accounts", __name__, url_prefix="/accounts")


@bp.route("/login")
def login():
    form = accounts_form.LoginForm()
    return render_template("/accounts/login.html", form=form)


@bp.route("/do-login", methods=["POST"])
def do_login():
    form = accounts_form.LoginForm()
    if not form.validate_on_submit():
        return redirect(url_for("accounts.login", **form.errors))

    user = (
        models.db.session.query(users.User)
        .filter_by(
            email=form.email.data,
        )
        .first()
    )

    if not user:
        return redirect(url_for("accounts.login", message="invalid login"))

    if not check_password_hash(user.password, form.password.data):
        return redirect(url_for("accounts.login", message="invalid password"))

    login_user(user)

    return redirect(url_for("accounts.dashboard"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    form = accounts_form.RegisterForm()
    if not form.validate_on_submit():
        return render_template("/accounts/register.html", form=form)

    user = users.User()
    form.populate_obj(user)

    print(form.data)
    user.password = generate_password_hash(form.password.data, method="sha256")

    # db management
    models.db.session.add(user)
    models.db.session.commit()

    return redirect(url_for("accounts.login"))


@bp.route("/logout")
def logout():
    logout_user()
    return redirect("/")


@bp.route("/dashboard")
@login_required
def dashboard():
    folio_data = models.db.session.query(folios.Folio).all()
    return render_template("/base/dashboard.html", folio_data=folio_data)

web/views/classes.py
from flask import (
                Blueprint, 
                render_template, 
                request, redirect, 
                url_for
                )  

from flask_login import login_required



from forms import folios as folios_form
import models
from models import folios

bp = Blueprint("classes", __name__, url_prefix="/classes")

@bp.route('')
def index():
    return render_template("class/class.html")

web/views/folios.py
from flask import (
                Blueprint, 
                render_template, 
                request, redirect, 
                url_for
                )  

from flask_login import login_required



from forms import folios as folios_form
import models
from models import folios

bp = Blueprint("folios", __name__, url_prefix="/folios")

@bp.route('/create', methods=["GET", "POST"])
def create():
    form = folios_form.FolioForm()
    if not form.validate_on_submit():
        return render_template('/folios/create.html', form=form)

    folio = folios.Folio()
    form.populate_obj(folio)

    models.db.session.add(folio)
    models.db.session.commit()

    return redirect(url_for('accounts.dashboard'))

@bp.route("/<folio_id>/update", methods=["GET", "POST"])
def update(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id = folio_id,
        )
        .first()
    )

    form = folios_form.FolioForm(obj=folio)
    if not form.validate_on_submit():
        return render_template('/folios/create.html', form=form)

    form.populate_obj(folio)

    models.db.session.commit()

    return redirect(url_for('accounts.dashboard'))


@bp.route("/<folio_id>/delete")
def delete(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id = folio_id,
        )
        .first()
    )

    models.db.session.delete(folio)
    models.db.session.commit()

    return redirect(url_for('accounts.dashboard'))


@bp.route('/<folio_id>')
@login_required
def view(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id = folio_id,
        )
        .first()
    )

    return render_template('/folios/view.html', folio=folio)

web/templates/accounts/login.html
{% extends "/base/base-layout.html" %}

{% block default_head %}
<style>
.container {
  margin-top: 10em;
}

.form-signin {
  max-width: 330px;
  padding: 15px;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

</style>


  <div class="container">

<div class="text-center">
<main class="form-signin w-100 m-auto">
<form action="{{ url_for('accounts.do_login') }}" method="POST">
  {{ form.hidden_tag() }}
  <img class="mb-4" src="{{ url_for('static', filename='images/r202.png') }}" alt="" width="75">
  <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

  <div class="form-floating">
    <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
    <label for="floatingInput">Email address</label>
  </div>
  <div class="form-floating">
    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
    <label for="floatingPassword">Password</label>
  </div>

  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
</form>

{% if request.args | length > 0 %}
  <div  class="alert alert-danger" role="alert" style="margin-top: 10px;">
    <ul>
    {% for k, v in request.args.items() %}
      <li><b>{{ k }}: </b> {{ v }}</li>
    {% endfor %}
    </ul>
  </div>
{% endif %}

</main>
</div>

  </div>

{% endblock %}

web/templates/accounts/register.html
{% extends "/base/base-layout.html" %}

{% block default_head %}

<style>
.form-signin {
    max-width: 330px;
    padding: 15px;
}

.form-signin .form-floating:focus-within {
    z-index: 2;
}

.form-signin input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
    
</style>
        
<div class="container" style="margin-top: 5em;">
  <div class="text-center">
    <main class="form-signin w-100 m-auto">
      <form  method="POST">
        {{ form.hidden_tag() }}
        <img class="mb-4" src="{{ url_for('static', filename='images/r202.png') }}" alt="" width="70">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
    
        <div class="form-floating" style="margin-top: 1em;">
          {{ form.email(class_="form-control") }}
          <label for="floatingInput">Email address</label>
        </div>
        <div class="form-floating" style="margin-top: 1em;">
          {{ form.password(class_="form-control") }}
          <label for="floatingPassword">Password</label>
        </div>
    
        <div class="form-floating" style="margin-top: 1em;">
          {{ form.first_name(class_="form-control") }}
          <label for="floatingFirstname">Firstname</label>
        </div>
    
        <div class="form-floating" style="margin-top: 1em;">
          {{ form.last_name(class_="form-control") }}
          <label for="floatingLastName">LastName</label>
        </div>
    
        <button class="w-100 btn btn-lg btn-primary" type="submit" style="margin-top: 1em;">Register</button>
      </form>
      
      {% if request.args | length > 0 %}
        <div  class="alert alert-danger" role="alert" style="margin-top: 10px;">
          <ul>
          {% for k, v in request.args.items() %}
            <li><b>{{ k }}: </b> {{ v }}</li>
          {% endfor %}
          </ul>
        </div>
      {% endif %}
    </main>
  </div>
    
</div>
    
{% endblock %}

web/templates/base/base-layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Portfolio</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
        <link rel = "icon" href = "/static/images/superhero.png" type = "image/x-icon">
        <style>
            body {
                background: #E5E7EB;
                position: relative;
                width: 100%;
            }
        </style>
        {% block default_head %}{% endblock %}
    </head>
     
    <body>
        {% block body %}{% endblock %} 
    </body>
    {% block additional_js %}{% endblock %}
    
</html>

web/templates/base/dashboard.html
{% extends "/dashboard/index.html" %}

{% block content %}

<style>

.button {
  font-size: 1em;
  padding: 0.7em;
  margin: 0.7em;
  width: 7em;
  background: #111827;
  cursor: pointer;
  text-align: center;
  border-radius: 50px;
  box-shadow: 5px 10px 10px -1px rgba(12, 69, 112, 0.486),
              -5px -10px 10px -1px rgb(255, 255, 255, 0.70);
}

.button .button-view {
  text-decoration: none;
  color: #23ca37;
  font-weight: 700;
}

.button .button-edit {
  text-decoration: none;
  color: #e6e65d;
  font-weight: 700;
}

.button .button-delete{
  text-decoration: none;
  color: rgb(222, 42, 22);
  font-weight: 700;
}

</style>

{% for folio in folio_data %}

<div class="container" style="width: 40em; margin-top: 2em;">
  <div class="row">
    <main class="card">
      <div class="card-body">
        <div style="margin-top: 2em;">
          <h3 class="card-title" style="color: rgb(39, 190, 190);"># {{ folio.id }}</h3>
          <h5>Name: <h6>{{ folio.name }}</h6></h5>
          <h5>Email: <h6>{{ folio.email }}</h6></h5>
          <h5>Biography: <h6>{{ folio.biography }}</h6></h5>
          <h5>Education: <h6>{{ folio.education }}</h6></h5>
          <h5>Skills: <h6>{{ folio.skills }}</h6></h5>
          <td>
            <div class="row" style="margin: 3em;">
              <div class="col">
                <div class="button">
                  <a href="{{ url_for('folios.view', folio_id=folio.id) }}" class="button-view">View</a>
                </div>
              </div>
              <div class="col">
                <div class="button">
                  <a href="{{ url_for('folios.update', folio_id=folio.id) }}" class="button-edit">Edit</a>
                </div>
              </div>
              <div class="col">
                <div class="button">
                  <a href="{{ url_for('folios.delete', folio_id=folio.id) }}" class="button-delete">Delete</a>
                </div>
              </div>
            </div>
          </td>
        </div>
      </div>
    </main>
  </div>
</div>

{% endfor %}

{% endblock %}

web/templates/base/default-dashboard.html
{% extends "/base/base-layout.html" %}

{% block default_head %}{% endblock %}

{% block body %}

    {% block content_dashboard %}{% endblock %}
    
{% endblock %}

web/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{{ url_for('static', filename='images/r202.png') }}" alt="" width="25" height="35">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('accounts.dashboard') }}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('accounts.register') }}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('accounts.login') }}">Login</a>
        </li>
    </div>
  </div>
</nav>

web/templates/class/class.html
{% extends "/dashboard/index.html" %}

{% block content %}

<style>

.container {
    margin-top: 10em;
}

</style>
    <div class="container">
        <form class="row g-3">
            <div class="col-md-6">
              <label for="inputEmail4" class="form-label">Email</label>
              <input type="email" class="form-control" id="inputEmail4">
            </div>
            <div class="col-md-6">
              <label for="inputPassword4" class="form-label">Password</label>
              <input type="password" class="form-control" id="inputPassword4">
            </div>
            <div class="col-12">
              <label for="inputAddress" class="form-label">Address</label>
              <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
            </div>
            <div class="col-12">
              <label for="inputAddress2" class="form-label">Address 2</label>
              <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
            </div>
            <div class="col-md-6">
              <label for="inputCity" class="form-label">City</label>
              <input type="text" class="form-control" id="inputCity">
            </div>
            <div class="col-md-4">
              <label for="inputState" class="form-label">State</label>
              <select id="inputState" class="form-select">
                <option selected>Choose...</option>
                <option>...</option>
              </select>
            </div>
            <div class="col-md-2">
              <label for="inputZip" class="form-label">Zip</label>
              <input type="text" class="form-control" id="inputZip">
            </div>
            <div class="col-12">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck">
                <label class="form-check-label" for="gridCheck">
                  Check me out
                </label>
              </div>
            </div>
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Sign in</button>
            </div>
        </form>
    </div>
{% endblock %}

web/templates/dashboard/index.html
{% extends "/base/default-dashboard.html" %}

{% block default_head %}

  <style>

  #menu .item {
    position: fixed;
    width: 300px;
    height: 100%;
    background: #111827;
    transition: 0.5s;
    overflow: hidden;

  }

  #menu .item.active {
    width: 90px;
  }

  #menu .item ul {
    position: absolute;
    top: 10px;
    left: -15px;
    width: 100%;
  }

  #menu .item ul li {
    position: relative;
    width: 200%;
    list-style: none;
    border-top-left-radius: 30px;
    border-bottom-left-radius: 30px;
  }

  #menu .item ul li:hover,
  #menu .item ul li.hovered {
    background: #E5E7EB;
  }

  #menu .item ul li:nth-child(1) {
    margin-bottom: 40px;
    pointer-events: none;
  }

  #menu .item ul li a {
    position: relative;
    display: block;
    width: 100%;
    display: flex;
    text-decoration: none;
    color: #fff;
  }

  #menu .item ul li:hover a,
  #menu .item ul li.hovered a {
    color: #111827;
  }

  #menu .item ul li a .icon {
    position: relative;
    display: block;
    min-width: 60px;
    height: 60px;
    line-height: 55px;
    text-align: center;
  }

  #menu .item ul li a .icon i {
    font-size: 1.5em;
  }

  #menu .item ul li a .title {
    position: relative;
    display: block;
    padding: 0 13px;
    height: 60px;
    line-height: 60px;
  }

  #menu .item ul li:hover a::before,
  #menu .item ul li.hovered a::before {
    content: '';
    position: absolute;
    right: 0;
    top: -50px;
    width: 50px;
    height: 50px;
    background: transparent;
    border-radius: 50%;
    box-shadow: 35px 35px 0 10px #E5E7EB;
    pointer-events: none;
  }

  #menu .item ul li:hover a::after,
  #menu .item ul li.hovered a::after {
    content: '';
    position: absolute;
    right: 0;
    top: -50px;
    width: 50px;
    height: 50px;
    background: transparent;
    border-radius: 50%;
    box-shadow: 35px -35px 0 10px #E5E7EB;
    pointer-events: none;
  }

  #interface .main {
    width: calc(100% - 300px);
    left: 300px;
    position: absolute;
    min-height: 100vh;
    transition: 0.5s;
  }

  #interface .main.active {
    width: calc(100% - 90px);
    left: 90px;
    
  }

  #interface .topbar {
    width: 100%;
    height: 60px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    background: #fff;
    padding: 15px 10px;
    border-bottom: 4px solid #594ef7;
  }

  #interface .toggle {
    position: relative;
    width: 60px;
    height: 60px;
    justify-content: center;
    align-items: center;
    font-size: 2em;
    cursor: pointer;

  }

  #interface .user {
    position: relative;;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    overflow: hidden;
    cursor: pointer;
  }

  #interface .user img {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  </style>

{% endblock %}

{% block additional_js %}

  <script>

    let toggle =document.querySelector('.toggle');
    let item =document.querySelector('.item');
    let main =document.querySelector('.main');

    toggle.onclick = function(){
      item.classList.toggle('active');
      main.classList.toggle('active');

    }


    let list = document.querySelectorAll('.item li');
    function activeLink(){
      list.forEach((item) => 
      item.classList.remove('hovered'));
      this.classList.add('hovered')
    }
    list.forEach((item) => 
    item.addEventListener('mouseover',activeLink));
  </script>

{% endblock %}



{% block content_dashboard %}

<section id="menu">
  <div class="item">
    <ul>
      <li>
        <a>
          <span class="icon"><i class="bi bi-archive"></i></span>
          <span class="title" style="font-weight: 500;">folio</span>
        </a>
      </li>
      <li>
        <a href="{{ url_for('accounts.dashboard')}}">
          <span class="icon"><i class="bi bi-pie-chart-fill"></i></span>
          <span class="title">Dashboard</span>
        </a>
      </li>
      <li>
        <a href="{{ url_for('classes.index')}}">
          <span class="icon"><i class="bi bi-archive-fill"></i></span>
          <span class="title">Class</span>
        </a>
      </li>
      <li>
        <a href="{{ url_for('folios.create')}}">
          <span class="icon"><i class="bi bi-file-earmark-plus-fill"></i></span>
          <span class="title">Folio</span>
        </a>
      </li>
      <li>
        <a href="{{ url_for('accounts.logout')}}">
          <span class="icon"><i class="bi bi-caret-left-square-fill"></i></span>
          <span class="title">Log out</span>
        </a>
      </li>
    </ul>
  </div>
</section>

<section id="interface">
  <div class="main">
    <div class="topbar">
      <div class="toggle">
        <i class="bi bi-list"></i>
      </div>
      <div class="user">
        <i class="bi bi-airplane-engines"></i>
      </div>
    </div>
    <div class="content">
      {% block content %}{% endblock %}
    </div>
  </div>
</section>


  
{% endblock %}

web/templates/folios/create.html
{% extends "/dashboard/index.html" %}

{% block content %}
  <style>
    
  .button-submit {
    font-size: 1em;
    padding: 0.7em;
    margin: 0.7em;
    width: 7em;
    background: #111827;
    cursor: pointer;
    text-align: center;
    border-radius: 50px;
    box-shadow: 5px 10px 10px -1px rgba(12, 69, 112, 0.486),
                -5px -10px 10px -1px rgb(255, 255, 255, 0.70);
    text-decoration: none;
    color: #9faeff;
    font-weight: 700;
  }

  </style>

<div class="container" style="width: 40em; margin-top: 2em;">
  <div class="row">
    <main class="card">
      <div class="card-body">
        <div style="margin-top: 2em;">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Add folio</h1>
          </div>

          <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3 row">
              <label for="staticEmail" class="col-sm-2 col-form-label">Name</label>
              <div class="col-sm-10">
                {{ form.name(class_="form-control") }}
              </div>
            </div>
            <div class="mb-3 row">
              <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
              <div class="col-sm-10">
                {{ form.email(class_="form-control") }}
              </div>
            </div>
            <div class="mb-3 row">
              <label for="staticEmail" class="col-sm-2 col-form-label">Biography</label>
              <div class="col-sm-10">
                {{ form.biography(class_="form-control") }}
              </div>
            </div>
            <div class="mb-3 row">
              <label for="staticEmail" class="col-sm-2 col-form-label">Education</label>
              <div class="col-sm-10">
                {{ form.education(class_="form-control") }}
              </div>
            </div>
            <div class="mb-3 row">
              <label for="staticEmail" class="col-sm-2 col-form-label">Skills</label>
              <div class="col-sm-10">
                {{ form.skills(class_="form-control") }}
              </div>
            </div>
            <button type="submit" class="button-submit">Submit</button>
          </form>
          
        </div>
      </div>
    </main>
  </div>
</div>
  
{% endblock %}

web/templates/folios/view.html
{% extends "/base/base-layout.html" %}

{% block default_head %}

  <header>
    {% include '/base/navbar.html' %}
  </header>

  <style>
  
  </style>

{% endblock %}
    
{% block body %}

<div class="container" style="width: 40em; margin-top: 2em;">
  <div class="row">
    <main class="card">
      <div class="card-body">
        <div style="margin-top: 2em;">
          <h3 class="card-title" style="color: rgb(39, 190, 190);"># {{ folio.id }}</h3>
          <ul>
            <li>{{ folio.name }}</li>
            <li>{{ folio.email }}</li>
            <li>{{ folio.biography }}</li>
            <li>{{ folio.education }}</li>
            <li>{{ folio.skills }}</li>
          </ul>
        </div>
      </div>
    </main>
  </div>
</div>
 

  


{% endblock %}